# Generated by Django 5.2.17 on 2026-08-25 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('description', models.TextField()),
                ('paid_to', models.CharField(blank=True, max_length=200)),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('voucher', 'كوبون'), ('other', 'أخرى')], default='cash', max_length=20)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='expenses/')),
                ('status', models.CharField(choices=[('pending', 'قيد الاعتماد'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sejel_expense',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('transaction_count', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sejel_pos_record',
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_liters', models.DecimalField(decimal_places=3, max_digits=12)),
                ('expected_sales', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_cash', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_vouchers', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_pos', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_collection', models.DecimalField(decimal_places=3, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=3, max_digits=12)),
                ('difference_type', models.CharField(choices=[('matched', 'مطابق'), ('surplus', 'فائض'), ('shortage', 'عجز')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد')], default='draft', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sejel_reconciliation',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('total_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sejel_voucher',
            },
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vouchercategory',
            options={'ordering': ['value']},
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='vouchercategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vouchercategory',
            name='name_en',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.station'),
        ),
        migrations.AddField(
            model_name='vouchercategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchercategory',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vouchercategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CashCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('time', models.DateTimeField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sejel_cash_collection',
                'ordering': ['-time'],
            },
        ),
    ]
