# Generated by Django 5.2.17 on 2026-08-26 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0002_cashcollection_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftFuelSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters_sold', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('expected_sales', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fueltype')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_breakdown', to='finance.reconciliation')),
            ],
            options={
                'db_table': 'sejel_shift_fuel_summary',
                'unique_together': {('reconciliation', 'fuel_type')},
            },
        ),
    ]
