# Generated by Django 5.2.17 on 2026-08-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_shiftfuelsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='net_cash',
            field=models.DecimalField(decimal_places=3, default=0, help_text='النقد المتبقي = التحصيل النقدي - المصروفات', max_digits=12),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='total_expenses',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
