# Generated by Django 5.2.17 on 2026-08-26 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tanktransfer'),
        ('finance', '0004_reconciliation_net_cash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(help_text='تاريخ تسليم الكوبونات للرحمة')),
                ('total_value', models.DecimalField(decimal_places=3, help_text='القيمة الإجمالية للكوبونات', max_digits=12)),
                ('total_count', models.PositiveIntegerField(help_text='عدد الكوبونات')),
                ('denom_5', models.PositiveIntegerField(default=0, help_text='عدد كوبونات 5 د.ل')),
                ('denom_6', models.PositiveIntegerField(default=0, help_text='عدد كوبونات 6 د.ل')),
                ('denom_8', models.PositiveIntegerField(default=0, help_text='عدد كوبونات 8 د.ل')),
                ('status', models.CharField(choices=[('submitted', 'تم التسليم'), ('paid', 'تم الدفع'), ('partial', 'دفع جزئي'), ('disputed', 'مختلف عليه'), ('cancelled', 'ملغى')], default='submitted', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=3, default=0, help_text='المبلغ المدفوع من الرحمة', max_digits=12)),
                ('payment_date', models.DateField(blank=True, help_text='تاريخ الدفع من الرحمة', null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='مرجع الدفع', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_settlements', to='core.station')),
            ],
            options={
                'db_table': 'sejel_voucher_settlement',
                'ordering': ['-submission_date', '-pk'],
            },
        ),
    ]
