# Generated by Django 5.2.17 on 2026-08-25 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], default='active', max_length=20)),
                ('shift_type', models.CharField(choices=[('morning', 'صباحي'), ('evening', 'مسائي'), ('full_day', 'كامل اليوم')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.station')),
            ],
            options={
                'db_table': 'sejel_employee',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.employee')),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.island')),
            ],
            options={
                'db_table': 'sejel_shift_assignment',
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]
