# Generated by Django 5.2.17 on 2026-08-25 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة'), ('under_review', 'تحت المراجعة')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='employees.employee')),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.island')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.station')),
            ],
            options={
                'db_table': 'sejel_shift',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_reading', models.DecimalField(decimal_places=3, max_digits=12)),
                ('end_reading', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('liters_sold', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meter_readings/')),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meter')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='shifts.shift')),
            ],
            options={
                'db_table': 'sejel_meter_reading',
            },
        ),
    ]
