# Generated by Django 5.2.17 on 2026-08-25 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='attendant',
            field=models.ForeignKey(blank=True, help_text='الموظف الفعلي المسجل عن القراءة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='recorded_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ ووقت تسجيل القراءة فعلياً', null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='island',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.island'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('scheduled', 'مجدولة'), ('open', 'مفتوحة'), ('in_progress', 'جارية'), ('submitted', 'مقدمة'), ('reconciled', 'تمت المطابقة'), ('closed', 'مغلقة'), ('cancelled', 'ملغاة'), ('under_review', 'تحت المراجعة')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='ShiftDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(help_text='يمكن أن تعبر منتصف الليل (مثال: 22:00 → 06:00)')),
                ('days', models.CharField(default='0,1,2,3,4,5,6', help_text='أيام الأسبوع مفصولة بفواصل، أرقام 0=الاثنين حتى 6=الأحد', max_length=13)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('default_employee', models.ForeignKey(blank=True, help_text='اختياري - الموظف الافتراضي لهذه المناوبة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_shift_definitions', to='employees.employee')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_definitions', to='core.station')),
            ],
            options={
                'db_table': 'sejel_shift_definition',
                'ordering': ['display_order', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='shifts.shiftdefinition'),
        ),
    ]
