# Generated by Django 5.2.17 on 2026-08-26 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shifts', '0002_meterreading_attendant_meterreading_recorded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdefinition',
            name='island',
            field=models.ForeignKey(blank=True, help_text='اختياري - إذا حددت جزيرة، تُنشأ مناوبات لهذه الجزيرة فقط', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.island'),
        ),
    ]
