# Generated by Django 5.2.17 on 2026-08-26 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_shiftdefinition_island'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='exception_authorized_by',
            field=models.ForeignKey(blank=True, help_text='المسؤول الذي صرّح بالاستثناء', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_meter_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='exception_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('reset', 'تصفير العداد'), ('replacement', 'استبدال العداد'), ('other', 'استثناء آخر')], help_text='نوع الاستثناء إذا كانت القراءة أقل من السابقة', max_length=20),
        ),
    ]
