# Generated by Django 5.2.17 on 2026-08-25 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'sejel_fuel_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('inactive', 'غير نشطة')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'sejel_island',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'sejel_marketing_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('profit_margin', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cost_per_liter', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.fueltype')),
            ],
            options={
                'db_table': 'sejel_fuel_price',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='core.island')),
            ],
            options={
                'db_table': 'sejel_machine',
                'ordering': ['number'],
                'unique_together': {('island', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('inactive', 'غير نشطة'), ('maintenance', 'صيانة')], default='active', max_length=20)),
                ('relationship_type', models.CharField(choices=[('owned', 'مملوكة للمواطن'), ('rented', 'مؤجرة من شركة التسويق'), ('agency', 'وكالة/إعادة بيع')], max_length=20)),
                ('cash_collection_mode', models.CharField(choices=[('during_shift', 'أثناء المناوبة'), ('end_of_shift', 'عند نهاية المناوبة')], default='during_shift', max_length=20)),
                ('target_cash_amount', models.DecimalField(decimal_places=3, default=500, max_digits=10)),
                ('photo_meter_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketing_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marketingcompany')),
            ],
            options={
                'db_table': 'sejel_station',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='island',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islands', to='core.station'),
        ),
        migrations.CreateModel(
            name='StationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islands_count', models.PositiveIntegerField(default=2)),
                ('machines_per_island', models.PositiveIntegerField(default=2)),
                ('meters_per_machine', models.PositiveIntegerField(default=2)),
                ('tanks_count', models.PositiveIntegerField(default=4)),
                ('cash_target_amount', models.DecimalField(decimal_places=3, default=500, max_digits=10)),
                ('photo_meter_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.station')),
            ],
            options={
                'db_table': 'sejel_station_settings',
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('current_level', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('last_reading_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fueltype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='core.station')),
            ],
            options={
                'db_table': 'sejel_tank',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('current_reading', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('inactive', 'غير نشطة'), ('maintenance', 'صيانة')], default='active', max_length=20)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fueltype')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='core.machine')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tank')),
            ],
            options={
                'db_table': 'sejel_meter',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدير النظام'), ('manager', 'مدير المحطة'), ('finance', 'المالي'), ('supervisor', 'المشرف')], default='supervisor', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.station')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sejel_user_profile',
            },
        ),
        migrations.AlterUniqueTogether(
            name='island',
            unique_together={('station', 'number')},
        ),
    ]
