# Generated by Django 5.2.17 on 2026-08-26 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tankreading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='الكمية المنقولة باللتر', max_digits=10)),
                ('transfer_date', models.DateTimeField(help_text='تاريخ ووقت النقل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.tank')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fueltype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_transfers', to='core.station')),
                ('to_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.tank')),
            ],
            options={
                'db_table': 'sejel_tank_transfer',
                'ordering': ['-transfer_date', '-pk'],
            },
        ),
    ]
