# Generated by Django 5.2.17 on 2026-08-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tanktransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low', 'رصيد منخفض'), ('critical', 'رصيد حرج'), ('empty', 'خزان فارغ'), ('full', 'خزان ممتلئ')], max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_alerts', to='core.station')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.tank')),
            ],
            options={
                'db_table': 'sejel_tank_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
