from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('guide/', views.user_guide, name='user_guide'),
    path('users/', views.users_list, name='users_list'),
    path('users/create/', views.user_create, name='user_create'),
    path('users/<int:pk>/edit/', views.user_edit, name='user_edit'),
    path('users/<int:pk>/delete/', views.user_delete, name='user_delete'),
    path('users/<int:pk>/toggle-active/', views.user_toggle_active, name='user_toggle_active'),
    path('login/', auth_views.LoginView.as_view(template_name='pages/auth/login.html'), name='login'),
    path('logout/', views.simple_logout, name='logout'),
    path('stations/', views.station_list, name='station_list'),
    path('stations/create/', views.station_create, name='station_create'),
    path('stations/<int:pk>/', views.station_detail, name='station_detail'),
    path('stations/<int:pk>/edit/', views.station_edit, name='station_edit'),
    path('stations/<int:pk>/delete/', views.station_delete, name='station_delete'),
    path('settings/fuel-types/', views.fuel_type_list, name='fuel_type_list'),
    path('settings/fuel-types/create/', views.fuel_type_create, name='fuel_type_create'),
    path('settings/fuel-types/<int:pk>/edit/', views.fuel_type_edit, name='fuel_type_edit'),
    path('settings/fuel-types/<int:pk>/delete/', views.fuel_type_delete, name='fuel_type_delete'),
    path('settings/fuel-prices/', views.fuel_price_list, name='fuel_price_list'),
    path('settings/fuel-prices/create/', views.fuel_price_create, name='fuel_price_create'),
    path('settings/fuel-prices/<int:pk>/edit/', views.fuel_price_edit, name='fuel_price_edit'),
    path('settings/fuel-prices/<int:pk>/delete/', views.fuel_price_delete, name='fuel_price_delete'),
    path('settings/voucher-categories/', views.voucher_category_list, name='voucher_category_list'),
    path('settings/voucher-categories/create/', views.voucher_category_create, name='voucher_category_create'),
    path('settings/voucher-categories/<int:pk>/edit/', views.voucher_category_edit, name='voucher_category_edit'),
    path('settings/voucher-categories/<int:pk>/delete/', views.voucher_category_delete, name='voucher_category_delete'),
    path('settings/marketing-companies/', views.marketing_company_list, name='marketing_company_list'),
    path('settings/marketing-companies/create/', views.marketing_company_create, name='marketing_company_create'),
    path('settings/marketing-companies/<int:pk>/edit/', views.marketing_company_edit, name='marketing_company_edit'),
    path('settings/marketing-companies/<int:pk>/delete/', views.marketing_company_delete, name='marketing_company_delete'),
    path('settings/islands/', views.island_list, name='island_list'),
    path('settings/islands/create/', views.island_create, name='island_create'),
    path('settings/islands/<int:pk>/edit/', views.island_edit, name='island_edit'),
    path('settings/islands/<int:pk>/delete/', views.island_delete, name='island_delete'),
    path('settings/machines/', views.machine_list, name='machine_list'),
    path('settings/machines/create/', views.machine_create, name='machine_create'),
    path('settings/machines/<int:pk>/edit/', views.machine_edit, name='machine_edit'),
    path('settings/machines/<int:pk>/delete/', views.machine_delete, name='machine_delete'),
    path('settings/meters/', views.meter_list, name='meter_list'),
    path('settings/meters/create/', views.meter_create, name='meter_create'),
    path('settings/meters/<int:pk>/edit/', views.meter_edit, name='meter_edit'),
    path('settings/meters/<int:pk>/delete/', views.meter_delete, name='meter_delete'),
    path('settings/expense-categories/', views.expense_category_list, name='expense_category_list'),
    path('settings/expense-categories/create/', views.expense_category_create, name='expense_category_create'),
    path('settings/expense-categories/<int:pk>/edit/', views.expense_category_edit, name='expense_category_edit'),
    path('settings/expense-categories/<int:pk>/delete/', views.expense_category_delete, name='expense_category_delete'),
]
