# Generated by Django 5.2.17 on 2026-08-26 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tankreading'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='invoiced_amount',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='قيمة الفاتورة/الشحنة بالدينار', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مدفوع'), ('partial', 'دفع جزئي'), ('paid', 'مدفوع')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.marketingcompany'),
        ),
    ]
