# Generated by Django 5.2.17 on 2026-08-26 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tankreading'),
        ('inventory', '0002_delivery_created_by_delivery_invoiced_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='تاريخ المطابقة')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, help_text='إجمالي الوارد (شحنات مستلمة) خلال الفترة', max_digits=12)),
                ('sold_quantity', models.DecimalField(decimal_places=3, default=0, help_text='إجمالي المبيعات من العدّادات المرتبطة بالخزان', max_digits=12)),
                ('theoretical_level', models.DecimalField(decimal_places=3, default=0, help_text='الرصيد النظري = آخر قراءة + وارد - مبيعات', max_digits=12)),
                ('actual_level', models.DecimalField(decimal_places=3, default=0, help_text='الرصيد الفعلي من قراءة الخزان', max_digits=12)),
                ('variance', models.DecimalField(decimal_places=3, default=0, help_text='الفرق = الفعلي - النظري', max_digits=12)),
                ('variance_type', models.CharField(choices=[('matched', 'مطابق'), ('surplus', 'فائض'), ('shortage', 'عجز')], default='matched', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد')], default='draft', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closing_reading', models.ForeignKey(blank=True, help_text='قراءة الخزان عند نهاية الفترة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closing_for_reconciliation', to='core.tankreading')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opening_reading', models.ForeignKey(help_text='قراءة الخزان عند بداية الفترة', on_delete=django.db.models.deletion.PROTECT, related_name='opening_for_reconciliation', to='core.tankreading')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_reconciliations', to='core.station')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_reconciliations', to='core.tank')),
            ],
            options={
                'db_table': 'sejel_fuel_reconciliation',
                'ordering': ['-date', '-pk'],
            },
        ),
    ]
