# Generated by Django 5.2.17 on 2026-08-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_fuelreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelreconciliation',
            name='transferred_in',
            field=models.DecimalField(decimal_places=3, default=0, help_text='إجمالي الوارد من تحويلات بين الخزانات', max_digits=12),
        ),
        migrations.AddField(
            model_name='fuelreconciliation',
            name='transferred_out',
            field=models.DecimalField(decimal_places=3, default=0, help_text='إجمالي الصادر من تحويلات بين الخزانات', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fuelreconciliation',
            name='theoretical_level',
            field=models.DecimalField(decimal_places=3, default=0, help_text='الرصيد النظري = آخر قراءة + وارد + تحويل وارد - تحويل صادر - مبيعات', max_digits=12),
        ),
    ]
