# Generated by Django 5.2.17 on 2026-08-26 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tankalert'),
        ('inventory', '0004_fuelreconciliation_transferred_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=3, help_text='الكمية المطلوبة باللتر', max_digits=10)),
                ('priority', models.CharField(choices=[('normal', 'عادي'), ('urgent', 'عاجل'), ('critical', 'حرج')], default='normal', max_length=20)),
                ('current_level', models.DecimalField(blank=True, decimal_places=3, help_text='مستوى الخزان عند الطلب', max_digits=10, null=True)),
                ('reason', models.TextField(blank=True, help_text='سبب الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('dispatched', 'تم الشحن'), ('received', 'تم الاستلام'), ('cancelled', 'ملغى')], default='pending', max_length=20)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fueltype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='core.station')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tank')),
            ],
            options={
                'db_table': 'sejel_delivery_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
