# Generated by Django 5.2.17 on 2026-08-27 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_audit_log'),
        ('inventory', '0005_deliveryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='remaining_on_truck',
            field=models.DecimalField(decimal_places=3, default=0, help_text='الكمية المتبقية في الشاحنة', max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='total_allocated',
            field=models.DecimalField(decimal_places=3, default=0, help_text='إجمالي الكمية الموزعة على الخزانات', max_digits=10),
        ),
        migrations.CreateModel(
            name='DeliveryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='الكمية المخصصة لهذا الخزان باللتر', max_digits=10)),
                ('pre_reading', models.DecimalField(blank=True, decimal_places=3, help_text='قراءة الخزان قبل التعبئة', max_digits=12, null=True)),
                ('post_reading', models.DecimalField(blank=True, decimal_places=3, help_text='قراءة الخزان بعد التعبئة', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.delivery')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tank')),
            ],
            options={
                'db_table': 'sejel_delivery_allocation',
                'ordering': ['tank__name'],
            },
        ),
    ]
